jetty:
  port: 10010

redis:
  host: localhost
  port: 6379
  password: redis

mysql:
  host: localhost
  port: 3306
  username: root
  password: root

rabbitmq:
  host: localhost
  username: admin
  password: admin

mybatis:
  path: mapper/mybatis-config.xml